export const fakeData = [
  {
    _id: '3',
    localize: {
      en: 'Cà Phê Arabica TCH (200gr)',
      vi: 'Cà Phê Nguyên Hạt Arabica TCH (200gr)',
    },
    description:
      'The Coffee House gửi bạn hương vị cà phê từ 100% hạt Arabica, được chọn lọc kỹ lưỡng tại vùng Cầu Đất, với độ cao 1650m. Với vị đắng nhẹ, hậu vị chua thanh, ngọt dịu, Cà phê nguyên hạt Arabica từ The Coffee House sẽ giúp bạn tạo ra những tách cà phê cold brew hay hand brew tinh tế yêu thích của riêng mình.',
    product_odoo: {
      product_tmpl_id: 2747,
      variants: [
        {
          code: '10070008',
          price: 100000,
          product_id: 2090,
          val: 'Khách hàng tự xay hạt tại nhà',
          localize: {
            en: 'Khách hàng tự xay hạt tại nhà',
            vi: 'Khách hàng tự xay hạt tại nhà',
          },
        },
        {
          code: '11020075',
          price: 100000,
          product_id: 2206,
          val: 'Cửa hàng xay sẵn hạt thành dạng bột',
          localize: {
            vi: 'Cửa hàng xay sẵn hạt thành dạng bột',
            en: 'Cửa hàng xay sẵn hạt thành dạng bột',
          },
        },
      ],
    },
    categ_id: [9, 18],
    topping_list: [],
    variants: [
      {
        code: '10070008',
        price: 100000,
        product_id: 2090,
        val: 'Khách hàng tự xay hạt tại nhà',
        localize: {
          en: 'Khách hàng tự xay hạt tại nhà',
          vi: 'Khách hàng tự xay hạt tại nhà',
        },
      },
      {
        code: '11020075',
        price: 100000,
        product_id: 2206,
        val: 'Cửa hàng xay sẵn hạt thành dạng bột',
        localize: {
          vi: 'Cửa hàng xay sẵn hạt thành dạng bột',
          en: 'Cửa hàng xay sẵn hạt thành dạng bột',
        },
      },
    ],
    type: [],
    options: [
      {
        name: 'Size',
        desciption: 'Chọn 1 loại size',
        min: 1,
        max: 1,
        default_index: 0,
        items: [
          {
            code: '10070008',
            price: 0,
            product_id: 2090,
            val: 'Khách hàng tự xay hạt tại nhà',
            localize: {
              en: 'Khách hàng tự xay hạt tại nhà',
              vi: 'Khách hàng tự xay hạt tại nhà',
            },
            is_main: true,
          },
          {
            code: '11020075',
            price: 0,
            product_id: 2206,
            val: 'Cửa hàng xay sẵn hạt thành dạng bột',
            localize: {
              vi: 'Cửa hàng xay sẵn hạt thành dạng bột',
              en: 'Cửa hàng xay sẵn hạt thành dạng bột',
            },
            is_main: true,
          },
        ],
      },
    ],
    codes: [],
    product_category_id: '100609fec3cd51c0000a7001d56',
    product_name: 'Test Cà Phê Nguyên Hạt Arabica TCH (200gr)',
    price: 100000,
    base_price: 100000,
    is_delivery: true,
    branch: 'TCH',
    slug: 'ca-phe-nguyen-hat-arabica-tch-200gr',
    created_at: '2019-10-01 14:10:00',
    updated_at: '2020-12-25 10:44:29',
    __v: 0,
    active: true,
    high_res_image: 'https://minio.thecoffeehouse.com/image/admin/Arabica_1_109041.jpg',
    image:
      'https://img5.thuthuatphanmem.vn/uploads/2021/12/03/anh-tra-sua-tu-chup-cute_023738507.jpg',
    is_pickup: true,
    is_menuset: true,
    stock: true,
    description_html:
      '<ul><li><strong><em>Tên sản phẩm:\t</em></strong><em> </em>\t<em>Cà phê nguyên hạt Arabica</em></li><li><strong><em>Quy cách đóng gói:</em></strong><em> Gói 200g</em></li><li><strong><em>Hướng dẫn sử dụng: </em></strong>\tXay nhỏ hạt cà phê đến mức mong muốn. Cold brew hoặc hand brew để ra ly cà phê ngon nhất.</li><li><strong><em>Bảo quản:\t</em></strong><em> </em>\t<em style="color: rgb(51, 51, 51);">Bảo quản sản phẩm nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.</em></li></ul><h3><br></h3><h3><strong style="color: rgb(255, 153, 0);">Điều gì làm nên hương vị nổi tiếng của cà phê nguyên hạt Abrabica?</strong></h3><p><span style="color: rgb(0, 0, 0);">Có bao giờ bạn tự hỏi, ly cà phê thơm ngát trên tay mình đã trải qua những chặng đường nào?</span></p><p><span style="color: rgb(0, 0, 0);">Đó là một hành trình dài và kỳ diệu từ việc chọn vùng đất hợp thổ nhưỡng, sàng lọc giống, tới trồng cây, chăm bón và thu hái.</span></p><p><span style="color: rgb(0, 0, 0);">Từ những cửa hàng đầu tiên, The Coffee House đã bắt đầu hợp tác với </span><em style="color: rgb(0, 0, 0);">Cầu Đất Farm</em><span style="color: rgb(0, 0, 0);"> để trồng cà phê theo tiêu chuẩn riêng. Vùng đất phủ sương nằm ở độ cao 1.650m so với mặt nước biển này là nơi tốt nhất để trồng giống cà phê Arabica ở Việt Nam. </span><em style="color: rgb(255, 153, 0);">Chính “độ cao vàng” ấy đã cho ra hạt cà phê Arabica thơm nhẹ, chua thanh tuyệt hảo.</em></p><p><span style="color: rgb(0, 0, 0);">Nhắc đến Arabica, người ta thường nghĩ đến một trải nghiệm đặc biệt với sự chuyển biến trong cảm nhận của người thưởng thức: </span><em style="color: rgb(0, 0, 0);">Vị chua thanh thấm dần vào khoang miệng sau đó kết thúc bằng vị ngọt trong trẻo.</em></p><p><span style="color: rgb(0, 0, 0);">Bên cạnh đó, bằng sự lai tạo giống, xử lý hạt, cách rang cũng như phương thức pha chế, cà phê Arabica cũng mang đến hương vị đặc trưng khác nhau, thỏa mãn vị giác của mỗi tín đồ cà phê.</span></p><p><strong style="color: rgb(255, 153, 0);"><em>The Coffee House đã sẵn sàng gửi đến bạn chút hương thơm nhẹ nhàng của cà phê Arabica rồi, đặt ngay để cảm nhận bạn nhé!</em></strong></p><p><em>Tìm hiểu thêm:</em><strong style="color: rgb(255, 153, 0);"><em> </em></strong><a href="https://tch.vn/blogs/6124e675ec53670001d9645c" rel="noopener noreferrer" target="_blank" style="background-color: rgb(255, 255, 255);">Nghệ thuật pha chế - Cold Brew</a></p><p><br></p>',
    hint_note: [],
    image_id: null,
    intro: {
      en: null,
      vi: null,
    },
    delivery_platform: [],
    description_html_en: null,
    thumbnails: [],
  },
  {
    _id: '2',
    localize: {
      en: 'The Coffee House Sữa Đá',
      vi: 'The Coffee House Sữa Đá',
    },
    description:
      'Thức uống giúp tỉnh táo tức thì để bắt đầu ngày mới thật hứng khởi. Không đắng khét như cà phê truyền thống, The Coffee House Sữa Đá mang hương vị hài hoà đầy lôi cuốn. Là sự đậm đà của 100% cà phê Arabica Cầu Đất rang vừa tới, biến tấu tinh tế với sữa đặc và kem sữa ngọt ngào cực quyến rũ. Càng hấp dẫn hơn với topping thạch 100% cà phê nguyên chất giúp giữ trọn vị ngon đến ngụm cuối cùng.',
    product_odoo: {
      product_tmpl_id: 7819,
      variants: [
        {
          code: '10020408',
          price: 49000,
          product_id: 2743,
          val: 'Lớn',
        },
        {
          code: '10020407',
          price: 45000,
          product_id: 2742,
          val: 'Vừa',
          localize: {
            en: null,
            vi: 'Size Vừa',
          },
        },
        {
          code: '10020406',
          price: 39000,
          product_id: 2741,
          val: 'Nhỏ',
          localize: {
            en: null,
            vi: 'Size Nhỏ',
          },
        },
      ],
    },
    categ_id: [1],
    topping_list: [
      {
        product_id: 1456,
        product_name: 'Test Kem Phô Mai Macchiato',
        code: '10100024',
        price: 10000,
      },
      {
        product_id: 196,
        product_name: 'Test Shot Espresso',
        code: '10100003',
        price: 10000,
      },
      {
        product_id: 1667,
        product_name: 'Test Trân châu trắng',
        code: '10100016',
        price: 10000,
      },
      {
        product_id: 10100019,
        product_name: 'Test Sốt Caramel',
        code: '10100019',
        price: 10000,
      },
      {
        product_name: 'Test Thạch Cà Phê',
        product_id: 10100031,
        code: '10100031',
        price: 10000,
        website_name: 'Thạch Cà Phê',
      },
    ],
    variants: [
      {
        code: '10020406',
        price: 39000,
        product_id: 2741,
        val: 'Nhỏ',
        localize: {
          en: null,
          vi: 'Nhỏ',
        },
      },
      {
        code: '10020407',
        price: 45000,
        product_id: 2742,
        val: 'Vừa',
        localize: {
          en: null,
          vi: 'Vừa',
        },
      },
      {
        code: '10020408',
        price: 49000,
        product_id: 2743,
        localize: {
          en: 'Lớn',
          vi: 'Lớn',
        },
        val: 'Lớn',
      },
    ],
    type: [],
    options: [
      {
        name: 'Size',
        desciption: 'Chọn 1 loại size',
        min: 1,
        max: 1,
        default_index: 1,
        items: [
          {
            code: '10020406',
            price: 0,
            product_id: 2741,
            val: 'Nhỏ',
            localize: {
              en: null,
              vi: 'Nhỏ',
            },
            is_main: true,
          },
          {
            code: '10020407',
            price: 6000,
            product_id: 2742,
            val: 'Vừa',
            localize: {
              en: null,
              vi: 'Vừa',
            },
            is_main: true,
          },
          {
            code: '10020408',
            price: 10000,
            product_id: 2743,
            localize: {
              en: 'Lớn',
              vi: 'Lớn',
            },
            val: 'Lớn',
            is_main: true,
          },
        ],
      },
      {
        name: 'Topping',
        desciption: 'Chọn tối đa 2 loại',
        min: 0,
        max: 2,
        default_index: -1,
        items: [
          {
            product_id: 1456,
            product_name: 'Test Kem Phô Mai Macchiato',
            code: '10100024',
            price: 10000,
            type: 3,
          },
          {
            product_id: 196,
            product_name: 'Test Shot Espresso',
            code: '10100003',
            price: 10000,
            type: 3,
          },
          {
            product_id: 1667,
            product_name: 'Test Trân châu trắng',
            code: '10100016',
            price: 10000,
            type: 3,
          },
          {
            product_id: 10100019,
            product_name: 'Test Sốt Caramel',
            code: '10100019',
            price: 10000,
            type: 3,
          },
          {
            product_name: 'Test Thạch Cà Phê',
            product_id: 10100031,
            code: '10100031',
            price: 10000,
            website_name: 'Thạch Cà Phê',
            type: 3,
          },
        ],
      },
    ],
    codes: [],
    product_category_id: '100609fec3cd51c0000a7001d43',
    product_name: 'Test The Coffee House Sữa Đá',
    price: 39000,
    base_price: 39000,
    active: true,
    branch: 'TCH',
    slug: 'the-coffee-house-sua-da',
    created_at: '2022-09-29 11:23:57',
    updated_at: '2022-10-03 16:14:35',
    __v: 2,
    description_html: null,
    description_html_en: null,
    hint_note: [],
    thumbnails: [],
    high_res_image: 'https://minio.thecoffeehouse.com/image/admin/1665655345_tch-sua-da.jpg',
    image:
      'https://img5.thuthuatphanmem.vn/uploads/2021/12/03/anh-tra-sua-tu-chup-cute_023738507.jpg',
    delivery_platform: ['TCH-POS-GRAB', 'TCH-POS-NOW', 'TCH-POS-GOJEK'],
    is_delivery: true,
    is_pickup: true,
    image_id: null,
  },
  {
    _id: '1',
    product_name: 'Test Cà Phê Sữa Đá',
    base_price: 29000,
    description:
      'Cà phê Đắk Lắk nguyên chất được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà, hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.',
    categ_id: [1, 72],
    branch: 'TCH',
    image_id: 180,
    image:
      'https://img5.thuthuatphanmem.vn/uploads/2021/12/03/anh-tra-sua-tu-chup-cute_023738507.jpg',
    variants: [
      {
        product_id: '100180',
        code: '10020012',
        price: 29000,
        val: 'Nhỏ',
        localize: {
          vi: 'Nhỏ',
          en: 'Small',
        },
      },
      {
        product_id: '100179',
        code: '10020011',
        price: 35000,
        val: 'Vừa',
        localize: {
          vi: 'Vừa',
          en: 'Medium',
        },
      },
      {
        code: '10020222',
        localize: {
          en: 'Large',
          vi: 'Lớn',
        },
        price: 39000,
        product_id: 10020222,
        val: 'Lớn',
      },
    ],
    updated_at: '2020-12-26 08:19:51',
    created_at: '2018-05-22 04:02:50',
    active: true,
    localize: {
      en: 'Ice Vietnamese Coffee With Condensed Milk',
      vi: 'Cà Phê Sữa Đá',
    },
    options: [
      {
        name: 'Size',
        desciption: 'Chọn 1 loại size',
        min: 1,
        max: 1,
        default_index: 1,
        items: [
          {
            product_id: '100180',
            code: '10020012',
            price: 0,
            val: 'Nhỏ',
            localize: {
              vi: 'Nhỏ',
              en: 'Small',
            },
            is_main: true,
          },
          {
            product_id: '100179',
            code: '10020011',
            price: 6000,
            val: 'Vừa',
            localize: {
              vi: 'Vừa',
              en: 'Medium',
            },
            is_main: true,
          },
          {
            code: '10020222',
            localize: {
              en: 'Large',
              vi: 'Lớn',
            },
            price: 10000,
            product_id: 10020222,
            val: 'Lớn',
            is_main: true,
          },
        ],
      },
      {
        name: 'Topping',
        desciption: 'Chọn tối đa 2 loại',
        min: 0,
        max: 2,
        default_index: -1,
        items: [
          {
            product_id: 1456,
            product_name: 'Test Kem Phô Mai Macchiato',
            code: '10100024',
            price: 10000,
            type: 3,
          },
          {
            product_id: 196,
            product_name: 'Test Shot Espresso',
            code: '10100003',
            price: 10000,
            type: 3,
          },
          {
            product_id: 1667,
            product_name: 'Test Trân châu trắng',
            code: '10100016',
            price: 10000,
            type: 3,
          },
          {
            product_id: 10100019,
            product_name: 'Test Sốt Caramel',
            code: '10100019',
            price: 10000,
            type: 3,
          },
          {
            product_name: 'Test Thạch Cà Phê',
            product_id: 10100031,
            code: '10100031',
            price: 10000,
            website_name: 'Thạch Cà Phê',
            type: 3,
          },
        ],
      },
    ],
    price: 29000,
    topping_list: [
      {
        product_id: 1456,
        product_name: 'Test Kem Phô Mai Macchiato',
        code: '10100024',
        price: 10000,
      },
      {
        product_id: 196,
        product_name: 'Test Shot Espresso',
        code: '10100003',
        price: 10000,
      },
      {
        product_id: 1667,
        product_name: 'Test Trân châu trắng',
        code: '10100016',
        price: 10000,
      },
      {
        product_id: 10100019,
        product_name: 'Test Sốt Caramel',
        code: '10100019',
        price: 10000,
      },
      {
        product_name: 'Test Thạch Cà Phê',
        product_id: 10100031,
        code: '10100031',
        price: 10000,
        website_name: 'Thạch Cà Phê',
      },
    ],
    type: [],
    slug: 'ca-phe-sua-da',
    high_res_image: 'https://minio.thecoffeehouse.com/image/admin/1639377738_ca-phe-sua-da.jpg',
    __v: 8,
    codes: [],
    product_category_id: '100609fec3cd51c0000a7001d43',
    product_odoo: {
      product_tmpl_id: 254,
      variants: [
        {
          code: '10020222',
          price: 39000,
          product_id: 1903,
          val: 'Lớn',
        },
        {
          code: '10020012',
          price: 29000,
          product_id: 180,
          val: 'Nhỏ',
        },
        {
          code: '10020011',
          price: 35000,
          product_id: 179,
          val: 'Vừa',
        },
      ],
    },
    is_menuset: true,
    is_delivery: true,
    is_pickup: true,
    stock: true,
    hint_note: ['Ít sữa', 'ít đá', 'ít ngọt', 'đá để riêng', 'không lấy ống hút & muỗng nhựa'],
    intro: {
      en: null,
      vi: null,
    },
    description_html:
      '<p><strong style="color: rgb(0, 0, 0); background-color: transparent;">Cà phê sữa đá - Sự độc đáo trong thưởng thức cà phê của người Việt</strong></p><p><br></p><p class="ql-align-justify"><em style="color: rgb(0, 0, 0); background-color: rgb(245, 245, 245);">Cà phê phin kết hợp cùng sữa đặc là một sáng tạo đầy tự hào của người Việt, được xem món uống thương hiệu của Việt Nam</em><span style="color: rgb(0, 0, 0); background-color: rgb(245, 245, 245);">.</span></p><p class="ql-align-justify"><span style="color: rgb(0, 0, 0); background-color: transparent;">Khi người Pháp đem văn hóa cà phê vào Việt Nam, người bản xứ thay thế sữa tươi đắt đỏ bằng sữa đặc rẻ tiền hơn để pha cùng cà phê. Tuy nhiên, bằng sự kết hợp hài hòa giữa các thái cực đắng – ngọt, bùi – béo, ly cà phê sữa đá lại sánh đặc và đậm đà hơn, không làm mất đi công dụng của cà phê mà bổ sung thêm năng lượng cho cơ thể từ sữa đã trở thành quen thuộc với nếp sống của người Việt và là một nét sáng tạo riêng, chinh phục được trái tim hàng triệu người yêu cà phê trên thế giới.</span></p><p class="ql-align-justify"><span style="color: rgb(0, 0, 0); background-color: transparent;">Nhà báo Nicola Graydon từng miêu tả và chia sẻ cảm nhận của mình trên tờ nhật báo nổi tiếng của Anh rằng: "Đó là loại cà phê mạnh, nhỏ giọt từ một phin kim loại nhỏ, bên dưới ly chứa khoảng ¼ lượng sữa đặc. Sau khoảng 15 phút, khi café ngừng nhỏ giọt, bạn sẽ khuấy đều và cho đá vào. Đầu tiên, tôi không chịu được cái ngọt kiểu như vậy. Tuy nhiên sau 3 ngày, tôi bị khuất phục và nghiện cái ngọt “thần thánh” ấy. Thật tuyệt vời khi cảm nhận cái ngọt thanh mát trong cuống họng, điều mà chúng ta không thấy ở một ly latte cổ điển”.</span></p><p class="ql-align-justify"><span style="color: rgb(0, 0, 0); background-color: transparent;">Cũng có người đã miêu tả Cà phê sữa đá rằng: Cà phê thì đắng mà sữa lại quá ngọt ngào. Hai vị đắng - ngọt như hương vị của cuộc sống, nên thưởng thức Cà phê sữa cũng giống như đang thưởng thức cuộc sống.</span></p><p class="ql-align-justify"><span style="color: rgb(0, 0, 0); background-color: transparent;">Và The Coffee House nghĩ rằng: Chằng có cách nào mô tả chính xác được mùi vị của Cà phê sữa Việt Nam hơn việc tự mình thưởng thức. Còn gì tuyệt vời hơn khi bắt đầu một ngày làm việc tràn đầy năng lượng hay tận hưởng ngày nghỉ của mình bằng một ly Cà phê sữa tinh tế đúng không nào!.</span></p><p><br></p><p><br></p>',
    thumbnails: ['https://minio.thecoffeehouse.com/image/admin/1645963560_ca-phe-sua-da-min.png'],
    delivery_platform: ['TCH-POS-GRAB', 'TCH-POS-NOW', 'TCH-POS-GOJEK'],
    description_html_en: null,
  },
]
